[package]
name = "turbocharged-dhbw"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Rudi Regentonne <@Rudi-Regentonne>"]
license = "MIT-0" 
description = "Typst template f√ºr die DHBW (in Anlehnung an die LaTeX-Vorlage)"
repository = "https://github.com/Rudi-Regentonne/DHBW-Typst-Template"
keywords = ["dhbw", "thesis"]
categories = ["paper", "thesis", "report"]
[template]
path = "template"
entrypoint = "main.typ"